SKYKit and SKYKitChat upgraded to 1.1.0
skygear-demo/swift-chat-uikit-demo pull request #10
Opened 2017-08-09 04:05 UTC by howawong

2017-08-09 08:05 UTC, rickmak requested changes
The user list is empty. And the generated query is wrong. What I get from the server log is 

```
[
    "and",
    [
        "neq",
        null,
        null
    ],
    [
        "neq",
        {
            "$type": "keypath",
            "$val": "_id"
        },
        "6601e8b4-e173-4b33-92ad-dbcbc10ea279"
    ]
]
```

2017-08-09 08:05 UTC, rickmak commented on Podfile
> +  pod 'SKYKit/Core', :git => 'https://github.com/SkygearIO/skygear-SDK-iOS.git', :tag => '1.1.0-alpha.0'
Please use release 1.1.0

2017-08-09 08:11 UTC, rickmak commented
The predicate is correct if the serach for name of user is not empty, and as follow:

```
    "predicate": [
        "and",
        [
            "ilike",
            {
                "$type": "keypath",
                "$val": "name"
            },
            "%rick%"
        ],
        [
            "neq",
            {
                "$type": "keypath",
                "$val": "_id"
            },
            "6601e8b4-e173-4b33-92ad-dbcbc10ea279"
        ]
    ],
```

2017-08-10 04:06 UTC, howawong commented
query bug fix in skygeario/chat-SDK-iOS#51

2017-08-10 07:49 UTC, merged